# Generated by Django 6.0 on 2025-12-13 07:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('engineering', 'Engineering'), ('marketing', 'Marketing'), ('sales', 'Sales'), ('hr', 'Human Resources'), ('finance', 'Finance'), ('operations', 'Operations')], max_length=50)),
                ('role', models.CharField(max_length=200)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('performance_score', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['department'], name='employees_e_departm_e28f46_idx'), models.Index(fields=['status'], name='employees_e_status_61c2f6_idx'), models.Index(fields=['is_archived'], name='employees_e_is_arch_2fdd71_idx')],
            },
        ),
    ]
